### ISSUE TITLE
KM emulation: no-go

### ISSUE THREAD

**Issue by Renohedron** [sb-ocr/diy-spacemouse#7]
Hi Salim, some time ago I built [Orbion](https://github.com/FaqT0tum/Orbion_3D_Space_Mouse) for exactly the same reasons you mention, but I never use it and always stick to my real SpaceMouse. The reason, which you maybe already realized if you used your DIY spacemouse for a bit, is you can't use keyboard/mouse emulation for a real work because your cursor, focus and everything is constantly taken away. I immediately noticed that by the end of your video, seeing mouse cursor slowly sliding away when you were rotating view. My point is that these devices are not much of use unless someone really dive into API you mentioned and program a full driver which doesn't emulate keystrokes and mouse movements. Any chance you would be interested in that after all?

**Comment by sb-ocr** [comment]
Hi @Renohedron, yes, you are right. It's indeed annoying when the cursor gets taken away. This project was more of an exploration, and it's evident that there is interest from many people in building something similar. For the next iteration, it will be crucial to have the full 6DOF sensing and a better integration.

Here's an idea I had: Instead of using KM, we could emulate a gamepad HID. In the report, we can include (x, y, z, Rx, Ry, Rz), and then work on an Add-in on Fusion's side that can read these coordinates and directly control the camera. This imo will be more practical for other users who want to make it compatible with different software or explore a different use case altogether.
